### ISSUE TITLE
stderr is not collected on error

### ISSUE THREAD

**Issue by lukasbestle** [sebastianbergmann/git#28]
[In the `execute()` method](https://github.com/sebastianbergmann/git/blob/master/src/Git.php#L136) you throw an exception if the return code is not 0. However the message is empty as `$output` only contains stdout, not stderr. I think you should collect stderr so that the actual Git error message can be passed to the exception.

**Comment by pedroborges** [comment]
You can redirect `stderr` to `stdout` by adding `2>&1` at end of the command. That way the error will be passed to the exception message.

_If you're using [kirby-autogit](https://github.com/pedroborges/kirby-autogit), I just pushed a fix to this._

**Comment by lukasbestle** [comment]
I know, that's what I'm using right now until there's a proper fix. The only issue is that the error output will be mixed with stdout, which might break code that depends on Git's output.
