### ISSUE TITLE
Wrong repository on packagist

### ISSUE THREAD

**Issue by andygrunwald** [sebastianbergmann/git#31]
We have added this repository in our medusa app to mirror it locally.
Medusa is requesting packagist.

If you have a look at the package.json file on packagist for this repository: https://packagist.org/packages/sebastian/git.json

You will see something like
```
"repository":"https:\/\/github.com\/sebastianbergmann"
```

If you compare this to e.g. X (https://packagist.org/packages/nelmio/cors-bundle.json), you see it like
```
"repository":"https:\/\/github.com\/nelmio\/NelmioCorsBundle"
```

Means: It seems to be point to an invalid repository.

Medusa will clone your repository and throw an exception:
```
 [Exception]
 Cloning into bare repository '/appdata/www/trivago/git-mirror/sebastian/git.git'...
 fatal: repository 'https://github.com/sebastianbergmann/' not found


add [--with-deps] [--] <package> [<config>]
```

My assumption: Someone is doing a str_replace of the string "git" somewhere. E.g. packagist?

**Comment by andygrunwald** [comment]
I posted this in packagist as well. See https://github.com/composer/packagist/issues/749
Not sure where the bug is

**Comment by stof** [comment]
IMO, the bug is in the URL stored in the DB on Packagist, probably because of a bad edit.

**Comment by andygrunwald** [comment]
@stof Any idea who to contact for a fix?

**Comment by stof** [comment]
@andygrunwald I think the bug was introduced by a DB cleanup done by Packagist maintainer actually, as mentioned in the Packagist issue. But both @sebastianbergmann and the Packagist maintainers should be able to fix it by editing the repository URL on Packagist

**Comment by andygrunwald** [comment]
Thank you @stof for the quick response.
@Seldaek and @sebastianbergmann: If i can help, ping me.

**Comment by andygrunwald** [comment]
Thx
